### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by microCloudCode** [andriinuts/medusa-plugin-variant-images#1]
![image](https://github.com/andriinuts/medusa-plugin-variant-images/assets/46712199/3f9d63d6-7e80-4fe6-a2ef-69ded247a5d5)
![image](https://github.com/andriinuts/medusa-plugin-variant-images/assets/46712199/862aa108-fed6-44f9-8b4f-92556ccea65a)

How to use this plugin? I've installed the required dependencies and configured it in medusa-config.js, but the admin interface doesn't seem to have changed.

**Comment by microCloudCode** [comment]
I've seen "Variants Images." How should it be implemented for the storefront? Is there any relevant documentation available?

**Comment by andriinuts** [comment]
> I've seen "Variants Images." How should it be implemented for the storefront? Is there any relevant documentation available?

In the storefront you will have `images` field inside each of the product variant. It's almost the same as you are using native product images but instead of product it's located inside a variant

**Comment by microCloudCode** [comment]
Thank you! I'm a bit confused between Media and Variants Images. When should Media be displayed in the storefront, and when should Variants Images be displayed? If you could explain their relationship, I would greatly appreciate it!
@andriinuts

**Comment by andriinuts** [comment]
> Thank you! I'm a bit confused between Media and Variants Images. When should Media be displayed in the storefront, and when should Variants Images be displayed? If you could explain their relationship, I would greatly appreciate it! @andriinuts

There is not direct relations and it's up to you. In my opinion you can have some shared images for all variants so you can upload them to the product images and upload variant only related images to the variant. I'm also planning to add possibility to upload thumbnail for the variant, as it will be helpful to display it in the cart or checkout page.

**Comment by microCloudCode** [comment]
Cool. It seems similar to Shopify, but in Shopify, adding variant images will automatically add them to Media. Additionally, it appears that Medusa doesn't natively support video resources.

**Comment by andriinuts** [comment]
Looks like this topic is closed
