### ISSUE TITLE
Thumbnail is String instead of Image entity

### ISSUE THREAD

**Issue by v0eak** [andriinuts/medusa-plugin-variant-images#10]
For some reason, the thumbnail is saved as a string in the database instead of being an Image entity like images is.

**Comment by andriinuts** [comment]
> For some reason, the thumbnail is saved as a string in the database instead of being an Image entity like images is.

yes, it's a string, the same as the product thumbnail. Why do you need it as an Image entity?

**Comment by v0eak** [comment]
Yes, I need it for my use case. I want to implement a feature where when the customer selects a variant, it shows the Variant Thumbnail in the Image preview. The image Component has a key which is the Id of the image from the looped product.images. Technically I could make it work with using the url instead, but it is just not as elegant. I have forked your repo and made this implementation myself, but somehow I introduced a bug, where I am now no longer able to edit any variants.

Product thumbnail should be Image as well imo, doesnt make sense for it to be a simple string if you have specifically an Image table in the database.

**Comment by andriinuts** [comment]
> Yes, I need it for my use case. I want to implement a feature where when the customer selects a variant, it shows the Variant Thumbnail in the Image preview. The image Component has a key which is the Id of the image from the looped product.images. Technically I could make it work with using the url instead, but it is just not as elegant. I have forked your repo and made this implementation myself, but somehow I introduced a bug, where I am now no longer able to edit any variants.
> 
> Product thumbnail should be Image as well imo, doesnt make sense for it to be a simple string if you have specifically an Image table in the database.

check how the thumbnail is implemented in the product from the medusa core, it's also just a string

**Comment by v0eak** [comment]
Yeh yeh, I'm just saying, it doesn't make sense for it to be, since there is specifically a table in the database for image entities. Idk, I just think it's not "clean"
