### ISSUE TITLE
Updating variant images from a batch job / import strategy

### ISSUE THREAD

**Issue by genox** [andriinuts/medusa-plugin-variant-images#12]
I made a PR #11  just now, please have a look when you have the time. 

Additionally, I made a few observations while trying to get a batch job working. But updating works for now.

What I am not sure about yet is how this acts when a variant is created while importing, but in this case, the import can simply be run twice for images to be attached.

> <strike>Another issue that I have is that imported images can't be removed from a variant in the UI. They are not listed in the modal. But since I rely primarily on imports to populate data and the source of truth is elsewhere, this is good enough for me.</strike>

Sorry, this is incorrect. Images can't be removed I think. But they are not listed

I previously added images using a script using the admin js client and while it successfully added images (it simply added .images, no other data was changed, I assume that would have caused me to look into why other properties were not changed earlier), the images were not visible in the modal.

**Comment by andriinuts** [comment]
> What I am not sure about yet is how this acts when a variant is created while importing, but in this case, the import can simply be run twice for images to be attached.

@genox probably it will require extra service rewriting. I was not playing with the product import. Thx for your contribution. We can close this ticket?

**Comment by andriinuts** [comment]
@genox your fixes updated in v1.0.5

**Comment by genox** [comment]
Thank you. Yeah this closes the ticket.
