### ISSUE TITLE
Image input is not showing

### ISSUE THREAD

**Issue by kaisiant** [andriinuts/medusa-plugin-variant-images#13]
The plugin seems not able to work with the current version, what can I do on my side? 
```
  "dependencies": {
    "@medusajs/admin": "7.1.9",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.7",
    "@medusajs/event-bus-redis": "^1.8.10",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/medusa": "1.19.0",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-file-s3": "^1.4.0",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.5",
    "medusa-plugin-variant-images": "^1.0.4",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  }
```

**Comment by andriinuts** [comment]
@kaisiant looks like you missed a few dependencies: 
`"medusa-react": "^9.0.4",
"@medusajs/ui": "^1.0.0",
"@medusajs/icons": "^1.0.0",`

**Comment by kaisiant** [comment]
Hi @andriinuts , I added the dependencies but the input still not showing. 

```
"dependencies": {
    "@medusajs/admin": "7.1.9",
    "@medusajs/cache-inmemory": "^1.8.9",
    "@medusajs/cache-redis": "^1.8.9",
    "@medusajs/event-bus-local": "^1.9.7",
    "@medusajs/event-bus-redis": "^1.8.10",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/icons": "^1.1.0",
    "@medusajs/medusa": "1.19.0",
    "@medusajs/ui": "^2.2.4",
    "@tanstack/react-query": "4.22.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "16.3.1",
    "express": "^4.17.2",
    "medusa-file-s3": "^1.4.0",
    "medusa-fulfillment-manual": "^1.1.38",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.24",
    "medusa-payment-stripe": "^6.0.5",
    "medusa-plugin-variant-images": "^1.0.4",
    "medusa-react": "^9.0.12",
    "prism-react-renderer": "^2.0.4",
    "typeorm": "^0.3.16"
  }
```

Am I looking at the correct place?
<img width="738" alt="image" src="https://github.com/andriinuts/medusa-plugin-variant-images/assets/26655111/62a2a7fe-c487-4e06-afdb-143be0df0bba">

**Comment by andriinuts** [comment]
> Hi @andriinuts , I added the dependencies but the input still not showing.
> 
> ```
> "dependencies": {
>     "@medusajs/admin": "7.1.9",
>     "@medusajs/cache-inmemory": "^1.8.9",
>     "@medusajs/cache-redis": "^1.8.9",
>     "@medusajs/event-bus-local": "^1.9.7",
>     "@medusajs/event-bus-redis": "^1.8.10",
>     "@medusajs/file-local": "^1.0.2",
>     "@medusajs/icons": "^1.1.0",
>     "@medusajs/medusa": "1.19.0",
>     "@medusajs/ui": "^2.2.4",
>     "@tanstack/react-query": "4.22.0",
>     "body-parser": "^1.19.0",
>     "cors": "^2.8.5",
>     "dotenv": "16.3.1",
>     "express": "^4.17.2",
>     "medusa-file-s3": "^1.4.0",
>     "medusa-fulfillment-manual": "^1.1.38",
>     "medusa-interfaces": "^1.3.7",
>     "medusa-payment-manual": "^1.0.24",
>     "medusa-payment-stripe": "^6.0.5",
>     "medusa-plugin-variant-images": "^1.0.4",
>     "medusa-react": "^9.0.12",
>     "prism-react-renderer": "^2.0.4",
>     "typeorm": "^0.3.16"
>   }
> ```
> 
> Am I looking at the correct place? <img alt="image" width="738" src="https://private-user-images.githubusercontent.com/26655111/294699673-62a2a7fe-c487-4e06-afdb-143be0df0bba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTc3MjgsIm5iZiI6MTcwNDU1NzQyOCwicGF0aCI6Ii8yNjY1NTExMS8yOTQ2OTk2NzMtNjJhMmE3ZmUtYzQ4Ny00ZTA2LWFmZGItMTQzYmUwZGYwYmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE2MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNzE5N2M3NmYxOWUxMTNhMTM2MjI0NzBiNWY2ZTUzMjU5ZGI2YTlhODFmYTk5MmZiMDIxZjdlNmVlZDdjZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BkeXzGp8-fZ4ZpkeqY2NjUGKE7PF_J0r82vroFSpAbE">

no, it should be displayed on the product detail page in the admin as one of the widgets like this one: 
![image](https://github.com/andriinuts/medusa-plugin-variant-images/assets/3611521/45bf9357-786c-4418-9911-27aea7129cc4)

**Comment by kaisiant** [comment]
> > Hi @andriinuts , I added the dependencies but the input still not showing.
> > ```
> > "dependencies": {
> >     "@medusajs/admin": "7.1.9",
> >     "@medusajs/cache-inmemory": "^1.8.9",
> >     "@medusajs/cache-redis": "^1.8.9",
> >     "@medusajs/event-bus-local": "^1.9.7",
> >     "@medusajs/event-bus-redis": "^1.8.10",
> >     "@medusajs/file-local": "^1.0.2",
> >     "@medusajs/icons": "^1.1.0",
> >     "@medusajs/medusa": "1.19.0",
> >     "@medusajs/ui": "^2.2.4",
> >     "@tanstack/react-query": "4.22.0",
> >     "body-parser": "^1.19.0",
> >     "cors": "^2.8.5",
> >     "dotenv": "16.3.1",
> >     "express": "^4.17.2",
> >     "medusa-file-s3": "^1.4.0",
> >     "medusa-fulfillment-manual": "^1.1.38",
> >     "medusa-interfaces": "^1.3.7",
> >     "medusa-payment-manual": "^1.0.24",
> >     "medusa-payment-stripe": "^6.0.5",
> >     "medusa-plugin-variant-images": "^1.0.4",
> >     "medusa-react": "^9.0.12",
> >     "prism-react-renderer": "^2.0.4",
> >     "typeorm": "^0.3.16"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Am I looking at the correct place? <img alt="image" width="738" src="https://private-user-images.githubusercontent.com/26655111/294699673-62a2a7fe-c487-4e06-afdb-143be0df0bba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTc3MjgsIm5iZiI6MTcwNDU1NzQyOCwicGF0aCI6Ii8yNjY1NTExMS8yOTQ2OTk2NzMtNjJhMmE3ZmUtYzQ4Ny00ZTA2LWFmZGItMTQzYmUwZGYwYmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE2MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNzE5N2M3NmYxOWUxMTNhMTM2MjI0NzBiNWY2ZTUzMjU5ZGI2YTlhODFmYTk5MmZiMDIxZjdlNmVlZDdjZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BkeXzGp8-fZ4ZpkeqY2NjUGKE7PF_J0r82vroFSpAbE">
> 
> no, it should be displayed on the product detail page in the admin as one of the widgets like this one: ![image](https://private-user-images.githubusercontent.com/3611521/294701339-45bf9357-786c-4418-9911-27aea7129cc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NjA0OTksIm5iZiI6MTcwNDU2MDE5OSwicGF0aCI6Ii8zNjExNTIxLzI5NDcwMTMzOS00NWJmOTM1Ny03ODZjLTQ0MTgtOTkxMS0yN2FlYTcxMjljYzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDZUMTY1NjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzU0MzNjM2U1YjMyOWE4OThmOGVjYTUzOWY3NGZlYzEwMTFlOTIzYmUzMzUyM2Y5ZDI1MDM1OTMxYWY5NTM3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wE6hb9BKfAMF-s_fWe1XfCZ4J8dQnHscU2ds4-1c_j8)

Got it, I need to save the product first and go to the detail page add the images. Thank you.
<img width="912" alt="image" src="https://github.com/andriinuts/medusa-plugin-variant-images/assets/26655111/0ddf8a74-16ca-4a54-a38e-61494708904a">
