### ISSUE TITLE
Element type is invalid: expected a string or class/function error message

### ISSUE THREAD

**Issue by blitze** [andriinuts/medusa-plugin-variant-images#3]
Hello,

I am getting the below error using medusa 1.15.0 and medusa admin 7:

![image](https://github.com/andriinuts/medusa-plugin-variant-images/assets/21600/f8229479-9f75-4328-b212-b754162b1b4e)

![image](https://github.com/andriinuts/medusa-plugin-variant-images/assets/21600/7ac3bd64-801e-4ef8-b9ab-9351d62683f1)

The issue seems to be with the following:
https://github.com/andriinuts/medusa-plugin-variant-images/blob/5034db5bfb79a1f8ffd89c27a8cded59cca9cb0b/src/admin/VariantsImages/VariantsImagesModal.tsx#L98

I changed `<FocusModal>` to `<FocusModal.Root>` and it fixed the problem

**Comment by andriinuts** [comment]
@blitze are you using `"@medusajs/ui": "^1.0.0"`? Or still beta version?

**Comment by blitze** [comment]
My apologies. I did not properly follow your instructions. I ran `yarn add @medusa/ui @medusa/icons medusa-react` and it fixed it. Sorry about that.
