### ISSUE TITLE
Expand variant Images

### ISSUE THREAD

**Issue by blitze** [andriinuts/medusa-plugin-variant-images#5]
I enabled the product categories plugin and as I understand it, in order to show the product categories when viewing a product, I need to expand the categories field. Doing so, unfortunately, removed all the relational data (like images, profiles, variants, etc) I was getting for free. I am now required to expand the product relations that I need like images, variants, etc. So I did the following:

`await medusa.products.list({
          expand: "categories,images,profiles,variants,variants.options,variants.prices,variants.images",
})
`

I get an error message that includes
`data: {
      type: 'invalid_data',
      message: 'Relations [variants.images] are not valid'
    }`

How do you expand the variant images field? Please help.

I am running medusa 1.15.1

**Comment by andriinuts** [comment]
@blitze  fixed in v1.0.1, now it should be possible to extend it.
